/**
 * Internal data store for popup UI. A `model` property of this store
 * is generated by a host application store from backgraund page.
 * In extension environment, some actions (defined in `externalActions`) are
 * not dispatched to local store, but for local development they do
 */
'use strict';

import {createStore, applyMiddleware} from 'redux';
import createLogger from 'redux-logger';
import {SESSION, REMOTE_VIEW} from 'extension-app/lib/action-names';
import {deepGet} from 'extension-app/lib/utils';
import {MODEL, UI} from './action-names';
import reducers from './reducers';

const port = connectToApp();
const externalActions = new Set([
    SESSION.TOGGLE_ENABLED, SESSION.UPDATE_DIRECTION, SESSION.UPDATE_FILE_MAPPING,
    SESSION.ADD_USER_STYLESHEET, SESSION.REMOVE_USER_STYLESHEET
]);

var enhancer = null;
var initialState = {
    model: {},
    ui: {
        remoteView: {messages: []}
    }
};

if (!port) { // no port, local development
    initialState.model = {
        enabled: true,
        page: 'http://localhost:9000',
        origin: 'http://localhost:9000',
        direction: 'both',
        browserFiles: [
            'http://localhost:9000/css/main.css',
            'http://localhost:9000/css/module/form.css'
        ],
        editorFiles: [
            '/home/projects/foo/css/main.css',
            '/home/projects/foo/css/assets/form.css',
            '/home/projects/foo/css/assets/inner.css',
            '/home/projects/foo/css/assets/guides.css'
        ],
        userStylesheets: {},
        mapping: {
            'http://localhost:9000/css/module/form.css': '/home/projects/foo/css/assets/inner.css'
        },
        remoteView: {
            state: 'connected'
        }
    };
}

if (process.env.NODE_ENV !== 'production') {
    enhancer = applyMiddleware(createLogger());
}

const store = createStore(reducers, initialState, enhancer);

export function dispatch(data) {
    if (data.type === UI.RV_START) {
        return startRemoteViewSession();
    }

    if (data.type === UI.RV_STOP) {
        return stopRemoteViewSession();
    }

    if (externalActions.has(data.type) && port) {
        return port.postMessage({action: 'store-update', data});
    }
    return store.dispatch(data);
}

export function subscribe(onChange, select) {
    let currentState;
    let handler = () => {
        let nextState = getState();
        if (typeof select === 'function') {
            nextState = select(nextState);
        } else if (typeof select === 'string') {
            // watching for a specific key in store
            nextState = getStateValue(select, nextState);
        }
        if (nextState !== currentState) {
            currentState = nextState;
            onChange(currentState);
        }
    };

    return store.subscribe(handler);
}

export function getState() {
    return store.getState();
}

export function getStateValue(key, state=getState()) {
    return deepGet(state, key);
}

function startRemoteViewSession(data) {
    console.log('requested session start with', data);
    return port.postMessage({action: 'start-rv-session', data});
}

function stopRemoteViewSession(data) {
    console.log('requested session stop with', data);
    return port.postMessage({action: 'stop-rv-session', data});
}

function connectToApp() {
    try {
        var port = chrome.runtime.connect({name: 'popup'});
        port.onMessage.addListener(message => {
            if (message && message.action === 'model-update') {
                dispatch({
                    type: MODEL.UPDATE,
                    model: message.data
                });
            }
        });
        return port;
    } catch (e) {
        console.warn(e);
    }
}
